FROM alpine:3.24

ENV PIP_BREAK_SYSTEM_PACKAGES=1

RUN apk add --no-cache nginx \
  nginx-mod-stream \
  python3 \
  py3-pip && \
  pip install --upgrade pip && \
  pip install Jinja2

RUN mkdir -p /etc/nginx/includes \
  && ln -sf /dev/stdout /var/log/nginx/access.log \
  && ln -sf /dev/stderr /var/log/nginx/error.log

COPY bootstrap.py /
COPY docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["nginx", "-g", "daemon off;"]
